### ISSUE TITLE
Late Stories?

### ISSUE THREAD

**Issue by liebermanbob** [RallyTechServices/milestone-apps#24]
I guess I'm questioning the value of having Late Stories include stories not scheduled. For those many of us who use traditional Scrum, where we only schedule one iteration at a time, Late Stories counts the whole product backlog for a milestone. That's of little use. Scheduled for an iteration after the milestone date... that makes perfect sense.

**Comment by jmartin-rally** [comment]
Thank you for your input. 

The code in this organization was for the most part created for a specific request from a customer and are provided here as examples.  We do not actively maintain these and provide no guarantee for performance or fitness-for-purpose.  I'm sorry if the chosen algorithms don't meet your needs.  If you would like the app to do something different, please feel free to fork the repository or contact your sales rep for a quote.
